2021-05-29 17:42:33,421 INFO    MainThread:29607 [wandb_setup.py:_flush():69] setting env: {}
2021-05-29 17:42:33,421 INFO    MainThread:29607 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-29 17:42:33,421 INFO    MainThread:29607 [wandb_init.py:_log_setup():336] Logging user logs to /home/mohan/research/masters/robotics/robolfd/examples/offline/wandb/run-20210529_174233-2lwux8fh/logs/debug.log
2021-05-29 17:42:33,422 INFO    MainThread:29607 [wandb_init.py:_log_setup():337] Logging internal logs to /home/mohan/research/masters/robotics/robolfd/examples/offline/wandb/run-20210529_174233-2lwux8fh/logs/debug-internal.log
2021-05-29 17:42:33,422 INFO    MainThread:29607 [wandb_init.py:init():369] calling init triggers
2021-05-29 17:42:33,422 INFO    MainThread:29607 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-29 17:42:33,422 INFO    MainThread:29607 [wandb_init.py:init():418] starting backend
2021-05-29 17:42:33,422 INFO    MainThread:29607 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-05-29 17:42:33,431 INFO    MainThread:29607 [backend.py:ensure_launched():132] starting backend process...
2021-05-29 17:42:33,434 INFO    MainThread:29607 [backend.py:ensure_launched():136] started backend process with pid: 29620
2021-05-29 17:42:33,435 INFO    MainThread:29607 [wandb_init.py:init():423] backend started and connected
2021-05-29 17:42:33,435 INFO    MainThread:29607 [wandb_init.py:init():465] updated telemetry
2021-05-29 17:42:33,435 INFO    MainThread:29607 [wandb_init.py:init():484] communicating current version
2021-05-29 17:42:33,802 INFO    MainThread:29607 [wandb_init.py:init():489] got version response upgrade_message: "wandb version 0.10.31 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-05-29 17:42:33,802 INFO    MainThread:29607 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-29 17:42:34,128 INFO    MainThread:29607 [wandb_init.py:init():522] starting run threads in backend
2021-05-29 17:42:34,996 INFO    MainThread:29607 [wandb_run.py:_console_start():1565] atexit reg
2021-05-29 17:42:34,996 INFO    MainThread:29607 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.REDIRECT
2021-05-29 17:42:34,996 INFO    MainThread:29607 [wandb_run.py:_redirect():1417] Redirecting console.
2021-05-29 17:42:34,997 INFO    MainThread:29607 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-29 17:42:34,997 INFO    MainThread:29607 [wandb_init.py:init():546] run started, returning control to user process
2021-05-29 17:42:37,904 INFO    MainThread:29607 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 1
2021-05-29 17:42:37,904 INFO    MainThread:29607 [wandb_run.py:_restore():1507] restore
2021-05-29 17:42:40,197 INFO    MainThread:29607 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 792
  total_bytes: 792
}

2021-05-29 17:42:40,299 INFO    MainThread:29607 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 792
  total_bytes: 792
}

2021-05-29 17:42:41,145 INFO    MainThread:29607 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 792
  total_bytes: 8266
}

2021-05-29 17:42:41,691 INFO    MainThread:29607 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8266
  total_bytes: 8266
}

2021-05-29 17:42:41,792 INFO    MainThread:29607 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8266
  total_bytes: 8266
}

2021-05-29 17:42:41,894 INFO    MainThread:29607 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8266
  total_bytes: 8266
}

2021-05-29 17:42:41,995 INFO    MainThread:29607 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8266
  total_bytes: 8266
}

2021-05-29 17:42:42,096 INFO    MainThread:29607 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8266
  total_bytes: 8266
}

2021-05-29 17:42:42,197 INFO    MainThread:29607 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 8266
  total_bytes: 8266
}

2021-05-29 17:42:43,239 INFO    MainThread:29607 [wandb_run.py:_show_files():1879] logging synced files
